### ISSUE TITLE
Analytics support

### ISSUE THREAD

**Issue by gabro** [buildo/web-seed#12]
Should we include support for Google Analytics, Heap, Mixpanel and others out of the box?

**Comment by giogonzo** [comment]
nope :tongue: 

well, web-seed should be eventually split in
- `<better name for framework>`: a lib, and
- `buildo/web-seed`: all the other stuff that we at buildo use for web apps, such as semantic, deploy friendly build system, localization, ... and maybe analytics

**Comment by gabro** [comment]
agreed.
Semantic, GA, i18n are all at the same "seed-level", whereas the "flux-like" library should be separated.

**Comment by gabro** [comment]
Closing for now
