### ISSUE TITLE
split the framework code from the web-seed code

### ISSUE THREAD

**Issue by gcanti** [buildo/web-seed#17]
The framework code should be in a its own repo

**Comment by giogonzo** [comment]
Should I take care of this?

Naming? @gabro
Could just be `web-framework` for now

Also, I'd extract two repos:
- `web-framework` for the strictly *framework* part
- `web-framework-utils` for the rest (`@authenticated('redirectState')`, `@anonymous('loginState')`, `@autobound`)

**Comment by gabro** [comment]
jerusalem?

**Comment by gcanti** [comment]
spirograph?

![design](https://chart.googleapis.com/chart?chl=digraph+design+%7B%0D%0A++++rankdir+%3D+BT%3B%0D%0A++++UI+-%3E+App+%5Blabel%3D%22queries%22%5D%3B%0D%0A++++App+-%3E+UI+%5Blabel%3D%22send+domain+models%22%5D%3B%0D%0A++++Db+-%3E+App+%5Blabel%3D%22send+get+data%22%5D%3B%0D%0A++++App+-%3E+API+%5Blabel%3D%22request+fetch+data%22%5D%3B%0D%0A++++API+-%3E+App+%5Blabel%3D%22send+fetch+data%22%5D%3B%0D%0A++++App+-%3E+Db+%5Blabel%3D%22request+get+data%22%5D%3B%0D%0A%0D%0A%7D%0D%0A&cht=gv)

**Comment by gabro** [comment]
spyro?
http://vignette3.wikia.nocookie.net/spyro/images/2/2e/175766-spyro_the_dragon_large.jpg/revision/latest?cb=20120202140353

**Comment by giogonzo** [comment]
working on this right now.. https://github.com/buildo/labonline/pull/42

`web-framework` aka `spyro`

**Comment by giogonzo** [comment]
should be ok :) waiting for comments before proceeding also on this repo

`README`s still tbd

**Comment by giogonzo** [comment]
as @gcanti suggests,
since we are somewhat implicitly relying on react-router route Handlers to collect the `getQuery` statics,
`web-framework` itself should depend on `react-router`.

At this point it doesn't make much sense to have `util` as a separated project

It would be great to not depend in any way on the `react-router` interface and jargon, but I'll leave this as an issue / future improvement

**Comment by giogonzo** [comment]
this is more or less done: branch `framework`.
Still some `require` issues with `tcomb-*`, @gcanti should look into this

**Comment by gcanti** [comment]
> Still some require issues with tcomb-*

Should be ok now
