### ISSUE TITLE
Add support for semantic as hot-reload module

### ISSUE THREAD

**Issue by gcanti** [buildo/web-seed#28]

**Comment by giogonzo** [comment]
should be already in place in https://github.com/buildo/labonline (except for semantic folder watch)

**Comment by ascariandrea** [comment]
I already have a working configuration for [lexdoit](https://github.com/buildo/lexdoit/blob/master/web/webpack.build.config.js).

**Comment by ascariandrea** [comment]
Closed by #36

**Comment by ascariandrea** [comment]
Closed by #36
